### ISSUE TITLE
Multiple warnings and errors in Swift 2

### ISSUE THREAD

**Issue by ghost** [flinto/RK4Spring#2]
Hey guys,

Could you please check the compilation for the class `RK4Spring` using `Swift 2`?
There are multiple warnings and errors:

```
warning: Colon Violation: Colons should be next to the identifier when specifying a type. (colon)
...

error: Variable Name Violation: Variable name should be between 3 and 40 characters long: 'x' (variable_name)
...
```

**Comment by naan** [comment]
You mean Swift 2.2?

**Comment by naan** [comment]
It has been converted to swift 2.3 in master.

swift3 support is still in branch:

https://github.com/flinto/Spring/tree/swift3
